---
language: python
python:
    - 2.7
services:
    - docker
install:
    - docker build -t keepalived-centos6-rpm-builder CentOS6
    - docker build -t keepalived-centos6-rpm-builder CentOS7
script:
    - docker run -ti --rm -v $PWD/Centos6/data:/data -v $PWD/CentOS6/assets/config:/config keepalived-centos6-rpm-builder start.sh
    - docker run -ti --rm -v $PWD/Centos7/data:/data -v $PWD/CentOS7/assets/config:/config keepalived-centos7-rpm-builder start.sh
